---
deployment: cf

# String '196.168.10.10' will be replaced with the real IP address

jobs:
- name: dea
  template:
  - dea_next
  - dea_logging_agent

properties:
  domain: 192.168.10.10.xip.io
  system_domain: 192.168.10.10.xip.io
  system_domain_organization: system_domain
  app_domains:
    - 192.168.10.10.xip.io

  networks:
    apps: default
    management: default

  etcd_ips: [192.168.10.10]
  leader_ip: 192.168.10.10

  nats:
    machines: [192.168.10.10]
    address: 192.168.10.10
    port: 4222
    user: nats
    password: 008b0ead71af
    authorization_timeout: 5

  dea: &dea
    max_memory: 4096
    memory_mb: 4084
    memory_overcommit_factor: 4
    disk_mb: 4096
    disk_overcommit_factor: 4
    directory_server_protocol: http

  dea_next: *dea

  loggregator_endpoint:
    shared_secret: 008b0ead71af
    host: 0.api.cf1.apps-eu-west-1.microbosh
    port: 3456
